'use client';

import { useRef, useState } from 'react';
import { useLineupStore } from '@/lib/store';
import { downloadJson, validateImportedData } from '@/lib/storage';

export default function SettingsPage() {
  const { present, loaded, dispatch } = useLineupStore();
  const inputRef = useRef<HTMLInputElement>(null);
  const [message, setMessage] = useState('');
  if (!loaded) return <main className="mx-auto max-w-3xl px-4 py-10"><div className="card h-80 animate-pulse" /></main>;
  return <main className="mx-auto max-w-3xl px-4 pb-24 pt-6 sm:px-6"><p className="label-caps text-coral">Workspace controls</p><h1 className="mt-1 text-3xl font-semibold tracking-editorial">Settings</h1><div className="mt-6 space-y-4"><section className="card p-5"><p className="label-caps">Data portability</p><h2 className="mt-2 text-lg font-semibold">Your data stays in this browser</h2><p className="mt-2 text-sm text-charcoal-soft">Export JSON for backup or move it to another device. Import replaces the current workspace.</p><div className="mt-4 flex flex-wrap gap-2"><button className="focus-ring rounded-full bg-coral px-4 py-2 text-sm font-semibold" onClick={() => downloadJson(present)}>Export JSON</button><button className="focus-ring rounded-full border border-white/10 px-4 py-2 text-sm hover:bg-white/[.06]" onClick={() => inputRef.current?.click()}>Import JSON</button><input ref={inputRef} type="file" accept="application/json" className="hidden" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { const parsed: unknown = JSON.parse(await file.text()); if (!validateImportedData(parsed)) throw new Error('Invalid lineup file'); if (window.confirm('Replace all current roster and sessions?')) { dispatch({ type: 'INIT', data: parsed }); setMessage('Imported successfully.'); } } catch { setMessage('Could not import that file.'); } event.target.value = ''; }} /></div>{message && <p className="mt-3 text-xs text-charcoal-soft">{message}</p>}</section><section className="card p-5"><p className="label-caps">Danger zone</p><h2 className="mt-2 text-lg font-semibold">Clear all data</h2><p className="mt-2 text-sm text-charcoal-soft">This removes every rower and lineup from local storage.</p><button className="focus-ring mt-4 rounded-full border border-red-300/30 px-4 py-2 text-sm text-red-200 hover:bg-red-400/10" onClick={() => { if (window.confirm('Clear all data? This cannot be undone.')) { if (window.confirm('Really clear the entire workspace?')) dispatch({ type: 'INIT', data: { version: 1, rowers: [], sessions: [] } }); } }}>Clear all data</button></section><section className="card p-5"><p className="label-caps">About</p><p className="mt-2 text-sm text-charcoal-soft">Lineup Builder is a local-first tool for Stanford rowing coaches. The storage adapter is isolated so a Supabase adapter can replace localStorage later.</p></section></div></main>;
}
